services:
  backend:
    build: ./
    container_name: depoiq
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - depo_iq

  redis:
    image: redis:latest
    container_name: depoiq-redis
    ports:
      - "6379:6379"
    networks:
      - depo_iq
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
networks:
  depo_iq:
    driver: bridge
